CREATE TABLE `mfg_project` (
  `mfg_proj_id` int(11) NOT NULL,
  `mfg_proj_ref_no` varchar(30) NOT NULL,
  `cust_no` int(11) NOT NULL,
  `h_version` int(11) NOT NULL DEFAULT '0',
  `start_date` datetime NOT NULL,
  `end_date` datetime NOT NULL,
  `entry_id` int(11) NOT NULL,
  `entry_datetime` datetime NOT NULL,
  `loc_no` int(11) DEFAULT NULL,
  `approved_budget` double DEFAULT NULL,
  `status` varchar(20) DEFAULT NULL,
  `signer_id` int(11) DEFAULT NULL,
  `sign_datetime` datetime DEFAULT NULL,
  `comment` varchar(100) DEFAULT NULL,
  `auto_release_flag` char(1) DEFAULT NULL,
  `chg_status` varchar(20) DEFAULT NULL,
  `margin` double NOT NULL DEFAULT '0',
  `adv_fcst` char(1) DEFAULT NULL,
  `pool_flag` char(1) DEFAULT NULL,
  `cust_fcst` char(1) NOT NULL DEFAULT 'N',
  `project_type` char(1) NOT NULL DEFAULT 'M',
  `auto_bom` char(1) NOT NULL DEFAULT 'N',
  `standalone` char(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`mfg_proj_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8